version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= 
    volumes:
      - ${PLEX_CONFIG}:/config
      - /home/ayman/Documents/new_projet_docker/plex/tvseries:/tv
      - /home/ayman/Documents/new_projet_docker/plex/movies:/movies
    restart: unless-stopped
    networks:
      - plex_network


  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${OVERSEERR_CONFIG}:/config
    ports:
      - 5055:5055
    networks:
      - plex_network
    restart: unless-stopped


networks:
  plex_network:
    external: true